directories:
  output: dist3
  buildResources: build
appId: com.mofasa.app
productName: MoFASA
files:
  - filter:
      - public/**/*
      - main.js
      - preload.js
      - index.html
      - package.json
      - data/**/*
      - src/**/*
      - dist/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
  category: public.app-category.productivity
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
asar: true
asarUnpack:
  - '**/*.node'
  - data/**/*
npmRebuild: true
buildDependenciesFromSource: true
electronVersion: 28.3.3
